/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./components/core/appbar.vue')['default']
    AppBar: typeof import('./components/core/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChangeRateChip: typeof import('./components/core/ChangeRateChip.vue')['default']
    copy: typeof import('./components/core/CreateMissionDialog copy.vue')['default']
    CreateFOBMissions: typeof import('./components/core/CreateFOBMissions.vue')['default']
    CreateMissionDialog: typeof import('./components/core/CreateMissionDialog.vue')['default']
    FobThumb: typeof import('./components/core/FobThumb.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MissionCard: typeof import('./components/core/MissionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/core/SideBar.vue')['default']
    WeaponSelector: typeof import('./components/core/WeaponSelector.vue')['default']
    WeaponSelectorOption: typeof import('./components/core/WeaponSelectorOption.vue')['default']
  }
}
