/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/aircrafts': RouteRecordInfo<'/admin/aircrafts', '/admin/aircrafts', Record<never, never>, Record<never, never>>,
    '/components': RouteRecordInfo<'/components', '/components', Record<never, never>, Record<never, never>>,
    '/createFob': RouteRecordInfo<'/createFob', '/createFob', Record<never, never>, Record<never, never>>,
    '/viewFob': RouteRecordInfo<'/viewFob', '/viewFob', Record<never, never>, Record<never, never>>,
    '/viewMissionSet': RouteRecordInfo<'/viewMissionSet', '/viewMissionSet', Record<never, never>, Record<never, never>>,
  }
}
